version: "3.8"

services:
  node:
    container_name: node
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./apps/frontend:/apps/frontend

  rust:
    container_name: rust
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    env_file: ./apps/backend/.env
    ports:
      - "8001:8001"
    volumes:
      - ./apps/backend:/apps/backend