import { Theme } from "@radix-ui/themes";

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};
import "@radix-ui/themes/styles.css";

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="ja">
			<body>
				<Theme
					appearance="light"
					accentColor="teal"
					grayColor="gray"
					radius="large"
				>
					{children}
				</Theme>
			</body>
		</html>
	);
}
