import { Theme } from "@radix-ui/themes";

import "@radix-ui/themes/styles.css";
import StyledComponentsRegistry from "./hooks/Provider/StyledComponentProvider";

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="ja">
			<meta
				name="viewport"
				content="width=device-width,initial-scale=1.0,minimum-scale=1.0"
			/>
			<body>
				<Theme
					appearance="light"
					accentColor="teal"
					grayColor="gray"
					radius="large"
				>
					<StyledComponentsRegistry>{children}</StyledComponentsRegistry>
				</Theme>
			</body>
		</html>
	);
}
