[package]
name = "infrastructure"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# axum = { version = "0.6.20" }
async-graphql = "6.0.11"
sqlx = { version = "0.7.3", features = ["postgres"] }
domain = { path = "../domain" }
